name: Publish cloudbuildx:latest

on:
  push:
    branches: [main]

jobs:
  push-to-registry:
    name: push-cloudbuildx
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: misorobotics/cloudbuildx:latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: misorobotics/cloudbuildx:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push multiarch Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: misorobotics/cloudbuildx:multiarch
          labels: ${{ steps.meta.outputs.labels }}
          build-args: MULTIARCH=1
